server:
  port: 8001


spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_boot?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机版
      #defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,
  instance:
    #server上显示的名称
    instance-id: payment8001
    #访问路径可以显示ip
    prefer-ip-address: true
    #eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30s）
    lease-renewal-interval-in-seconds: 1
    #eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认为90s），超时将剔除服务
    lease-expiration-duration-in-seconds: 2


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.itcc.cloud.entities #所有entity别名类所在包
