#8004表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 8004

#服务别名---注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: 192.168.31.59:2181
  datasource:
    url: jdbc:mysql://localhost:3306/db_boot?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型